#!/usr/bin/env bash
# Bootstrap Icarus + Verilator without root: use system tools if present,
# else apt-get download + dpkg -x into .toolchain/. Writes .toolchain/env.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TC="$ROOT/.toolchain"
ENVF="$TC/env.sh"

have() { command -v "$1" >/dev/null 2>&1; }

# yosys + berkeley-abc + Nangate45 are needed only by scripts/synth.sh.
# Fetched on every path, but never fatally: a missing synthesis extra must
# not break the simulator bootstrap.
fetch_synth_deps() {
  local lib="$TC/lib/Nangate45_typ.lib"
  if [ ! -s "$lib" ]; then
    mkdir -p "$TC/lib"
    # -f: an HTTP error page must fail the fetch, not get cached as the library
    curl -fsL -o "$lib" \
      https://raw.githubusercontent.com/The-OpenROAD-Project/OpenROAD/master/test/Nangate45/Nangate45_typ.lib \
      || echo "note: could not fetch Nangate45; scripts/synth.sh will explain" >&2
    [ -s "$lib" ] || rm -f "$lib"
  fi
  if ! have yosys || ! have berkeley-abc; then
    if command -v apt-get >/dev/null && command -v dpkg >/dev/null; then
      mkdir -p "$TC/debs" "$TC/opt"
      (
        cd "$TC/debs"
        for pkg in yosys berkeley-abc; do
          ls "${pkg}"_*.deb >/dev/null 2>&1 || apt-get download "$pkg" \
            || echo "note: could not download $pkg; scripts/synth.sh will explain" >&2
        done
        for d in yosys_*.deb berkeley-abc_*.deb; do
          if [ -e "$d" ]; then
            dpkg -x "$d" "$TC/opt" || echo "note: could not extract $d" >&2
          fi
        done
      )
    else
      echo "note: no apt-get; install yosys + berkeley-abc yourself if you want scripts/synth.sh" >&2
    fi
  fi
}

mkdir -p "$TC"          # $ENVF lives here; needed on the system-toolchain path too

if have iverilog && have verilator; then
  echo "# system toolchain" > "$ENVF"
  echo "iverilog:  $(command -v iverilog)"
  echo "verilator: $(command -v verilator)"
  fetch_synth_deps
  echo "Using the system toolchain; wrote a no-op $ENVF"
  exit 0
fi

if ! command -v apt-get >/dev/null || ! command -v dpkg >/dev/null; then
  echo "No system iverilog/verilator, and this is not a Debian-based system." >&2
  echo "Install 'iverilog' and 'verilator' with your package manager, then" >&2
  echo "re-run this script -- it will detect them and do nothing else." >&2
  exit 1
fi

mkdir -p "$TC/debs" "$TC/opt"
cd "$TC/debs"

# libbz2 is an iverilog runtime dep missing from slim images. These three
# are REQUIRED, so a failure aborts; synthesis extras are fail-soft above.
for pkg in iverilog verilator libbz2-1.0; do
  ls "${pkg}"_*.deb >/dev/null 2>&1 || apt-get download "$pkg"
done

for d in "$TC"/debs/*.deb; do dpkg -x "$d" "$TC/opt"; done

fetch_synth_deps

# Verilator's perl wrapper resolves $VERILATOR_ROOT/verilator_bin and
# $VERILATOR_ROOT/bin/verilator_includer. The Debian package splits those
# across /usr/bin and /usr/share, so rebuild the layout with symlinks.
VROOT="$TC/vroot"
mkdir -p "$VROOT"
ln -sfn "$TC/opt/usr/share/verilator/include" "$VROOT/include"
ln -sfn "$TC/opt/usr/share/verilator/bin"     "$VROOT/bin"
for b in verilator_bin verilator_bin_dbg verilator_coverage_bin_dbg; do
  [ -e "$TC/opt/usr/bin/$b" ] && ln -sfn "$TC/opt/usr/bin/$b" "$VROOT/$b"
done

# iverilog needs -B pointing at its ivl helper programs, which are not on any
# default search path once the package is unpacked outside /usr.
IVL_DIR="$(find "$TC/opt/usr/lib" -maxdepth 3 -type d -name 'ivl' | head -1)"
if [ -z "$IVL_DIR" ]; then
  echo "Could not locate the ivl helper directory under $TC/opt/usr/lib." >&2
  echo "The iverilog package layout has changed; -B would be empty and every" >&2
  echo "iverilog invocation would fail in a confusing way. Aborting." >&2
  exit 1
fi

cat > "$ENVF" <<EOF
# generated by scripts/setup_toolchain.sh -- source this before running sims
export PATH="$TC/opt/usr/bin:\$PATH"
export LD_LIBRARY_PATH="$TC/opt/usr/lib/x86_64-linux-gnu:\${LD_LIBRARY_PATH:-}"
export VERILATOR_ROOT="$VROOT"
export IVL_B="-B $IVL_DIR"
export IVL_M="-M $IVL_DIR"
EOF

echo "Toolchain ready. Wrote $ENVF"
# shellcheck disable=SC1090
source "$ENVF"
iverilog $IVL_B -V | head -1
verilator --version
